/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liracs;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;

/**
 *
 * @author rafael
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public TelaPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        FUNDOBRANCO = new javax.swing.JPanel();
        CABECALHO = new javax.swing.JPanel();
        titulomenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        l_config = new javax.swing.JLabel();
        area = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        perfilimagem = new javax.swing.JLabel();
        MENU = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        l_listar = new javax.swing.JLabel();
        l_adicionar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        l_conta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FUNDOBRANCO.setBackground(new java.awt.Color(255, 255, 255));
        FUNDOBRANCO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CABECALHO.setBackground(new java.awt.Color(0, 73, 76));
        CABECALHO.setPreferredSize(new java.awt.Dimension(700, 50));
        CABECALHO.setLayout(null);

        titulomenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titulomenu.setForeground(new java.awt.Color(255, 255, 255));
        titulomenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CABECALHO.add(titulomenu);
        titulomenu.setBounds(280, 30, 120, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIRACS");
        CABECALHO.add(jLabel1);
        jLabel1.setBounds(280, 0, 120, 50);

        l_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_settings_white_36dp.png"))); // NOI18N
        l_config.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                config(evt);
            }
        });
        CABECALHO.add(l_config);
        l_config.setBounds(640, 0, 36, 50);

        FUNDOBRANCO.add(CABECALHO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        area.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(630, 550));
        jPanel1.setName(""); // NOI18N

        perfilimagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/chopper.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(perfilimagem)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(perfilimagem)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        area.add(jPanel1);
        jPanel1.setBounds(-10, 0, 630, 550);

        FUNDOBRANCO.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 630, 550));

        MENU.setBackground(new java.awt.Color(0, 220, 229));
        MENU.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 2, Color.BLACK));
        MENU.setPreferredSize(new java.awt.Dimension(70, 550));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Listar");
        MENU.add(jLabel2);

        l_listar.setForeground(new java.awt.Color(255, 255, 255));
        l_listar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_list_black_48dp.png"))); // NOI18N
        l_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista(evt);
            }
        });

        l_adicionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_add_circle_outline_black_48dp.png"))); // NOI18N
        l_adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Adicionar");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Conta");

        l_conta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_conta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_person_black_48dp.png"))); // NOI18N
        l_conta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conta(evt);
            }
        });

        javax.swing.GroupLayout MENULayout = new javax.swing.GroupLayout(MENU);
        MENU.setLayout(MENULayout);
        MENULayout.setHorizontalGroup(
            MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l_conta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(l_adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(l_listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MENULayout.setVerticalGroup(
            MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENULayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(l_listar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(73, 73, 73)
                .addComponent(l_adicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(64, 64, 64)
                .addComponent(l_conta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        FUNDOBRANCO.add(MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLayeredPane1.add(FUNDOBRANCO);
        FUNDOBRANCO.setBounds(0, 0, 700, 600);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        setSize(new java.awt.Dimension(700, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void config(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_config
        // TODO add your handling code here:
        TelaConfigurar obj = new TelaConfigurar();
        area.add(obj);
        obj.setVisible(true);
        titulomenu.setText("Configurações");
        l_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_settings_black_36dp.png")));
        l_listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_list_black_48dp.png"))); // NOI18N
        l_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_add_circle_outline_black_48dp.png"))); // NOI18N
        l_conta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_person_black_48dp.png"))); // NOI18N

    }//GEN-LAST:event_config

    private void add(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add
        TelaAdicionar obj = new TelaAdicionar();
        area.add(obj);
        obj.setVisible(true);
        titulomenu.setText("Adicionar Comando");
        //.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/ic_person_black_48dp.png")));
        l_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_settings_white_36dp.png")));
        l_listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_list_black_48dp.png"))); // NOI18N
        l_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_add_circle_outline_white_48dp.png"))); // NOI18N
        l_conta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_person_black_48dp.png"))); // NOI18N
    }//GEN-LAST:event_add

    private void conta(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conta
        TelaConta obj = new TelaConta();
        area.add(obj);
        obj.setVisible(true);
        titulomenu.setText("Configurar Conta");
        l_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_settings_white_36dp.png")));
        l_listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_list_black_48dp.png"))); // NOI18N
        l_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_add_circle_outline_black_48dp.png"))); // NOI18N
        l_conta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_person_white_48dp.png"))); // NOI18N
    }//GEN-LAST:event_conta

    private void lista(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista
        TelaListar obj = new TelaListar();
        area.add(obj);
        obj.setVisible(true);
        titulomenu.setText("Listar");
        l_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_settings_white_36dp.png")));
        l_listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_list_white_48dp.png"))); // NOI18N
        l_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_add_circle_outline_black_48dp.png"))); // NOI18N
        l_conta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/icones/ic_person_black_48dp.png"))); // NOI18N
    }//GEN-LAST:event_lista
    private static void ed(){
        TelaEditar obj = new TelaEditar();
        area.add(obj);
        obj.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CABECALHO;
    private javax.swing.JPanel FUNDOBRANCO;
    private javax.swing.JPanel MENU;
    private static javax.swing.JDesktopPane area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_adicionar;
    private javax.swing.JLabel l_config;
    private javax.swing.JLabel l_conta;
    private javax.swing.JLabel l_listar;
    private javax.swing.JLabel perfilimagem;
    private javax.swing.JLabel titulomenu;
    // End of variables declaration//GEN-END:variables
    public static void edita(){
        ed();
    }

}

