/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liracs.view.interfaces;

import Liracs.shared.model.domain.Comando;
import Liracs.shared.model.domain.InstrucaoComando;
import Liracs.shared.model.domain.InstrucaoGravada;
import Liracs.shared.util.exceptions.PersistenciaException;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import liracs.view.Stub.StubComando;
import liracs.view.Stub.StubInstrucaoComando;
import liracs.view.Stub.StubInstrucaoGravada;
import liracs.view.util.Capture;
import liracs.view.util.SaveAudio;

/**
 *
 * @author user
 */
public class TelaAdicionar extends javax.swing.JInternalFrame {

    private boolean gravando = false;
    private final Long userLoggedID;

    Capture capt;

    /**
     * Creates new form T_Adicionar
     */
    public TelaAdicionar(Long userID) {
        this.userLoggedID = userID;               //id do usuário
        capt = new Capture();
        capt.start();                       //já q é o beta mesmo, deixa eu corrigir um bug aqui <3
        capt.stop();                        //pára de rir e vai tomar café :v
        capt.zeraAis();                     //limpa o buffer do anti-bug

        initComponents();
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        gravar = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setResizable(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 550));

        jPanel3.setBackground(new java.awt.Color(0, 146, 152));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Descrição do Comando");

        jTextArea2.setColumns(15);
        jTextArea2.setRows(5);
        jTextArea2.setTabSize(6);
        jTextArea2.setName(""); // NOI18N
        jScrollPane2.setViewportView(jTextArea2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Gravar");

        gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_keyboard_voice_black_48dp.png")));
        gravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gravar(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        StubComando stubComando = new StubComando();
        ArrayList<Comando> listComando;
        try {
            listComando = stubComando.listarTodos();
            Vector v = new Vector();
            for(int i=0; i< listComando.size(); i++) {
                v.addElement(listComando.get(i).getDes_Comando());  //descricoes[i] = listComando.get(i).getDes_Comando();
            }
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(v));
        } catch (PersistenciaException ex) {
            Logger.getLogger(TelaAdicionar.class.getName()).log(Level.SEVERE, null, ex);
        }
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_home_black_48dp.png")));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telaprincipal(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(gravar)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4))
                    .addComponent(gravar))
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(0, 0, 630, 550);

        setSize(new java.awt.Dimension(632, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        /*StubComando stubComando = new StubComando();
         ArrayList<Comando> listComando;
         try {
         listComando = stubComando.listarTodos();
         for(int i=0; i< listComando.size(); i++) {
         jComboBox2.addItem(listComando.get(i).getDes_Comando());
                
         }
         } catch (PersistenciaException ex) {
         Logger.getLogger(TelaAdicionar.class.getName()).log(Level.SEVERE, null, ex);
         } */
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void gravar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gravar
        if (!gravando) {
            gravando = true;
            capt.start();
            gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_keyboard_voice_white_48dp.png")));
        } else {
            capt.stop();
            gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_keyboard_voice_black_48dp.png")));
            gravando = false;
        }

    }//GEN-LAST:event_gravar

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Evento cancelar
        if (gravando) {
            capt.stop();
            gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_keyboard_voice_black_48dp.png")));
            gravando = !gravando;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //evento botao salvar

        SaveAudio save = new SaveAudio();
        if (gravando) {              //Controle do microfone
            capt.stop();
            gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liracs/view/icones/ic_keyboard_voice_black_48dp.png")));
            gravando = false;
        }
        if (capt.getAis() != null) {      //Controle de criação de arquivo
            save.SaveToFile(capt.getAis());
        } else {
            System.out.println("Problemas durante a gravação. Contate o administrador do Sistema.");
            this.initComponents();
        }                               //Controle de inserção no BD  -> instrucao Gravada
        InstrucaoGravada instrucaoGravada = new InstrucaoGravada();
        instrucaoGravada.setAudio(save.getFile());
        instrucaoGravada.setDesc_Comando_Voz(jTextArea2.getText());
        instrucaoGravada.setCod_Usuario(userLoggedID);
        instrucaoGravada.setEnd_Comando_Voz(save.getFile().getAbsolutePath());
        StubInstrucaoGravada stubInstrucaoGravada = new StubInstrucaoGravada();
        Long instrucaoID = (long)0;
        try {
            instrucaoID = stubInstrucaoGravada.inserir(instrucaoGravada);
            this.setVisible(false);
        } catch (PersistenciaException ex) {
            Logger.getLogger(TelaAdicionar.class.getName()).log(Level.SEVERE, null, ex);
        }
        //  Controle de inserção no BD - InstrucaoComando
        System.out.println(jComboBox2.getSelectedItem());
        Long idComand = (long)0;
        try {
            ArrayList<Comando> listComando = new ArrayList<>();
            StubComando stubComando = new StubComando();
            listComando = stubComando.listarTodos();
            int preguica =0;
                //identifica qual o comando escolhido
            for(int i = 0; i< listComando.size(); i++) {
                if(jComboBox2.getSelectedItem().equals(listComando.get(i).getDes_Comando())){
                    idComand = listComando.get(i).getCod_Comando();
                    preguica = i;
                }
            }
            InstrucaoComando instrucaoComando = new InstrucaoComando();
            /*
            System.out.println("idComand = "+idComand);
            System.out.println("preguica = "+preguica);
            */
            instrucaoComando.setCod_Usuario(userLoggedID);
            instrucaoComando.setCod_Instrucao(instrucaoID);
            instrucaoComando.setInstrucaoGravada(instrucaoGravada);
            instrucaoComando.setComando(listComando.get(preguica));
            
            StubInstrucaoComando stubInstrucaoComando = new StubInstrucaoComando();
            stubInstrucaoComando.inserir(instrucaoComando);
        } catch (PersistenciaException ex) {
            Logger.getLogger(TelaAdicionar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void telaprincipal(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telaprincipal
        // TODO add your handling code here:
    }//GEN-LAST:event_telaprincipal

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gravar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
